const characterNames = [
    "Acheron",
    "Argenti",
    "Blade",
    "Boothill",
    "Caelus",
    "Dan Heng Imbititor Lunae",
    "Feixiao",
    "Firefly",
    "Fu Xuan",
    "Huohuo",
    "Jade",
    "Jiaoqiu",
    "Jingliu",
    "Kafka",
    "Lingsha",
    "Misha",
    "Moze",
    "Seele",
    "Sparkle",
    "Stelle",
    "Yunli",
    "Arlan",
    "Asta",
    "Aventurine",
    "Bailu",
    "Black Swan",
    "Bronya",
    "Clara",
    "Dan Heng",
    "Dr Ratio",
    "Gallagher",
    "Gepard",
    "Guinaifen",
    "Hanya",
    "Herta",
    "Himeko",
    "Hook",
    "Jing Yuan",
    "Luka",
    "Luocha",
    "Lynx",
    "March 7th",
    "Natasha",
    "Pela",
    "Qingque",
    "Robin",
    "Ruan Mei",
    "Sampo",
    "Serval",
    "Silver Wolf",
    "Sushang",
    "Tingyun",
    "Topaz",
    "Unknown",
    "Welt",
    "Xueyi"
];

export default characterNames