const contactInfo = [
    { chatName: 'Caelus', chatDesc: "I LOVE TRASH" },
    { chatName: 'Stelle', chatDesc: "I LOVE TRASH" },
    { chatName: 'Acheron', chatDesc: "Time for Departure" },
    { chatName: 'Aglaea', chatDesc: "See you at the baths" },
    { chatName: 'Anaxa', chatDesc: "Then let me ask you" },
    { chatName: 'Archer', chatDesc: "AAA-rank Professional Housekeeper" },
    { chatName: 'Argenti', chatDesc: "I swear to a rose" },
    { chatName: 'Arlan', chatDesc: "Peppy's emergency contact" },
    { chatName: 'Asta', chatDesc: "I shouldn't buy any more stuff..." },
    { chatName: 'Aventurine', chatDesc: "Always open to pull for your game account" },
    { chatName: 'Bailu', chatDesc: "Drink more warm water and get fewer tempers!" },
    { chatName: 'Black Swan', chatDesc: "Memories are soft amber" },
    { chatName: 'Blade', chatDesc: " " },
    { chatName: 'Boothill', chatDesc: "Pier Point Standard Heist (LFG 3/4)" },
    { chatName: 'Bronya', chatDesc: "In a meeting" },
    { chatName: 'Cerydra', chatDesc: "TBR" },
    { chatName: 'Castorice', chatDesc: "Writing as we speak" },
    { chatName: 'Cipher', chatDesc: "Show me the money!" },
    { chatName: 'Clara', chatDesc: "I want to go on a picnic with everyone (>▽<)" },
    { chatName: 'Dan Heng', chatDesc: "For anything related to the data bank, come find me." },
    { chatName: 'Dan Heng Imbititor Lunae', chatDesc: "For anything related to the data bank, come find me." },
    { chatName: 'Dr Ratio', chatDesc: '"There\'s no rush."'},
    { chatName: 'Feixiao', chatDesc: "Itching for a fight" },
    { chatName: 'Firefly', chatDesc: "I will find a dream that is mine..." },
    { chatName: 'Fugue', chatDesc: " " },
    { chatName: 'Fu Xuan', chatDesc: "I do not divine personal fortunes!" },
    { chatName: 'Gallagher', chatDesc: "Penaconian Dog" },
    { chatName: 'Gepard', chatDesc: "Working, apologies for the slow response" },
    { chatName: 'Guinaifen', chatDesc: "Not causing trouble, not fearing trouble, and no crazy challenges" },
    { chatName: 'Hanya', chatDesc: "Engaging in oneiromancy, do not disturb." },
    { chatName: 'Herta', chatDesc: "This account is disabled | Business Contact: Asta" },
    { chatName: 'Himeko', chatDesc: "I can survive without water, but coffee is my lifeblood" },
    { chatName: 'Hook', chatDesc: "Moles! Assemble at the Fight Club!" },
    { chatName: 'Huohuo', chatDesc: 'Mr. Tail\'s "Tail"'},
    { chatName: 'Hyacine', chatDesc: "The Twilight Courtyard, always by your side~" },
    { chatName: 'Hysilens', chatDesc: "TBR" },
    { chatName: 'Jade', chatDesc: "You are always welcome to Bonajade Exchange." },
    { chatName: 'Jiaoqiu', chatDesc: "There's no problem that a hot pot can't fix." },
    { chatName: 'Jing Yuan', chatDesc: "I'm not at the Seat of Divine Foresight" },
    { chatName: 'Jingliu', chatDesc: " " },
    { chatName: 'Kafka', chatDesc: " " },
    { chatName: 'Lingsha', chatDesc: "Don't get angry, don't get mad, you don't have the time to feel so bad" },
    { chatName: 'Luka', chatDesc: "No timely reply means I'm in training." },
    { chatName: 'Luocha', chatDesc: "A simple traveling merchant" },
    { chatName: 'Lynx', chatDesc: "The user you have messaged is currently unavailable" },
    { chatName: 'March 7th', chatDesc: "Today is also March 7th~" },
    { chatName: 'Misha', chatDesc: "Keep it up! The new world is just ahead!" },
    { chatName: 'Moze', chatDesc: "No signature." },
    { chatName: 'Mydei', chatDesc: "30% Training, 70% Diet" },
    { chatName: 'Natasha', chatDesc: "Doing outpatient runs at the Robot Settlement. Check my availability before you visit" },
    { chatName: 'Pela', chatDesc: "Please include your name when providing information" },
    { chatName: 'Phainon', chatDesc: "Praise the sun!" },
    { chatName: 'Qingque', chatDesc: "Go ahead and work, just don't interrupt my game" },
    { chatName: 'Rappa', chatDesc: "Heart unmoved, evil pursued" },
    { chatName: 'Robin', chatDesc: "Let's share our wings with one another." },
    { chatName: 'Ruan Mei', chatDesc: "Those are new cakes... Where did you get them?" },
    { chatName: 'Saber', chatDesc: "It is what it is, let's have a meal" },
    { chatName: 'Sampo', chatDesc: "Certified ancient relic agent" },
    { chatName: 'Seele', chatDesc: "If you have anything to say, spill it!" },
    { chatName: 'Serval', chatDesc: "Lacking sleep and inspiration" },
    { chatName: 'Silver Wolf', chatDesc: "Don't make a game if you don't know how to" },
    { chatName: 'Sparkle', chatDesc: " " },
    { chatName: 'Sunday', chatDesc: '♪ Listening to "Had I Not Seen the Sun"' },
    { chatName: 'Sushang', chatDesc: "What illness makes you sleepy as soon as you read a book?" },
    { chatName: 'Tingyun', chatDesc: "Let's talk it out and not fight~" },
    { chatName: 'Topaz', chatDesc: "Offsite~ Call if important, otherwise text" },
    { chatName: 'Tribbie', chatDesc: "Tribbie is always available~" },
    { chatName: 'Unknown', chatDesc: "???" },
    { chatName: 'Welt', chatDesc: "Everyone on the Express, please constantly keep in touch" },
    { chatName: 'Xueyi', chatDesc: "In seclusion. Do not disturb." },
    { chatName: 'Yanqing', chatDesc: "Did the Artisanship Commission have new products today? No" },
    { chatName: 'Yukong', chatDesc: "I wish to take to the skies once more..." },
    { chatName: 'Yunli', chatDesc: "(´・ω・`) Fight?" }
];

export default contactInfo;
