const stickerIDs = [
    { stickerId: 'PomPomHi', stickerURL: "https://i.postimg.cc/d3tGvGBj/Sticker-PPG-07-Pom-Pom-01.webp" },
    { stickerId: 'PomPomCry', stickerURL: "https://i.postimg.cc/Y9xQJd1S/Sticker-PPG-07-Pom-Pom-02.webp" },
    { stickerId: 'PomPomHeart', stickerURL: "https://i.postimg.cc/TPgVcd1g/Sticker-PPG-07-Pom-Pom-03.webp" },
    { stickerId: 'PomPomNo', stickerURL: "https://i.postimg.cc/V6wjGx0T/Sticker-PPG-07-Pom-Pom-04.webp" },
    { stickerId: 'PomPomYes', stickerURL: "https://i.postimg.cc/wjS5Jyq9/Sticker-PPG-07-Pom-Pom-05.webp" },
    { stickerId: 'PomPomLike', stickerURL: "https://i.postimg.cc/t41tYtHr/Sticker-PPG-07-Pom-Pom-06.webp" },
    { stickerId: 'PomPomQuestion', stickerURL: "https://i.postimg.cc/dtNjsNgk/Sticker-PPG-07-Pom-Pom-07.webp" },
    { stickerId: 'PomPomShock', stickerURL: "https://i.postimg.cc/gk2KPbtb/Sticker-PPG-07-Pom-Pom-08.webp" },
    { stickerId: 'PomPomSmart', stickerURL: "https://i.postimg.cc/BbMc1m6z/Sticker-PPG-07-Pom-Pom-09.webp" },
    { stickerId: 'PomPomGift', stickerURL: "https://i.postimg.cc/C5Fs13FD/Sticker-PPG-07-Pom-Pom-10.webp" },
    { stickerId: 'PomPomYum', stickerURL: "https://i.postimg.cc/05fC3yfC/Sticker-PPG-07-Pom-Pom-11.webp" },
    { stickerId: 'PomPomMusic', stickerURL: "https://i.postimg.cc/26NwpqM0/Sticker-PPG-07-Pom-Pom-12.webp" },
    { stickerId: 'PomPomPower', stickerURL: "https://i.postimg.cc/QMTbng4B/Sticker-PPG-07-Pom-Pom-13.webp" },
    { stickerId: 'PomPomWork', stickerURL: "https://i.postimg.cc/Sx5dr1rF/Sticker-PPG-07-Pom-Pom-14.webp" },
    { stickerId: 'PomPomShy', stickerURL: "https://i.postimg.cc/W1tS0c0w/Sticker-PPG-07-Pom-Pom-15.webp" },
    { stickerId: 'PomPomCurious', stickerURL: "https://i.postimg.cc/bNymNtJM/Sticker-PPG-07-Pom-Pom-16.webp" },
    { stickerId: 'PomPomTicket', stickerURL: "https://i.postimg.cc/B65CJSG4/Sticker-PPG-15-Pom-Pom-01.webp" },
    { stickerId: 'WubbabooCry', stickerURL: "https://i.postimg.cc/gJ4zZ798/Sticker-PPG-05-Wubbaboo-01.webp" },
    { stickerId: 'WubbabooShock', stickerURL: "https://i.postimg.cc/4dX4ng0X/Sticker-PPG-05-Wubbaboo-02.webp" },
    { stickerId: 'WubbabooBliss', stickerURL: "https://i.postimg.cc/436NJdB8/Sticker-PPG-05-Wubbaboo-03.webp" },
    { stickerId: 'WubbabooSleep', stickerURL: "https://i.postimg.cc/xdD1DHyJ/Sticker-PPG-05-Wubbaboo-04.webp" },
    { stickerId: 'WubbabooHeart', stickerURL: "https://i.postimg.cc/52F2RpvW/Sticker-PPG-05-Wubbaboo-05.webp" },
    { stickerId: 'WubbabooDown', stickerURL: "https://i.postimg.cc/pXSdC3mB/Sticker-PPG-05-Wubbaboo-06.webp" },
    { stickerId: 'WubbabooSpeechless', stickerURL: "https://i.postimg.cc/xT8CK91C/Sticker-PPG-05-Wubbaboo-07.webp" },
    { stickerId: 'WubbabooLike', stickerURL: "https://i.postimg.cc/VsDvrJ1p/Sticker-PPG-05-Wubbaboo-08.webp" },
    { stickerId: 'WubbabooDaze', stickerURL: "https://i.postimg.cc/Zn751MV4/Sticker-PPG-05-Wubbaboo-09.webp" },
    { stickerId: 'WubbabooHmph', stickerURL: "https://i.postimg.cc/GthpgCPX/Sticker-PPG-05-Wubbaboo-10.webp" },
    { stickerId: 'WubbabooQuestion', stickerURL: "https://i.postimg.cc/gJKJKJhw/Sticker-PPG-05-Wubbaboo-11.webp" },
    { stickerId: 'WubbabooBoo', stickerURL: "https://i.postimg.cc/RFmhffW5/Sticker-PPG-05-Wubbaboo-12.webp" },
    { stickerId: 'WubbabooPlot', stickerURL: "https://i.postimg.cc/K8dRGCFY/Sticker-PPG-05-Wubbaboo-13.webp" },
    { stickerId: 'WubbabooWow', stickerURL: "https://i.postimg.cc/LsLhnv63/Sticker-PPG-05-Wubbaboo-14.webp" },
    { stickerId: 'WubbabooStrict', stickerURL: "https://i.postimg.cc/bwGZjp7M/Sticker-PPG-05-Wubbaboo-15.webp" },
    { stickerId: 'WubbabooSmart', stickerURL: "https://i.postimg.cc/HsvrKVhX/Sticker-PPG-05-Wubbaboo-16.webp" },
];

export default stickerIDs
