export const characterNames = [
    "Unknown",
    "Stelle",
    "Caelus",
    "Acheron",
    "Argenti",
    "Arlan",
    "Asta",
    "Aventurine",
    "Bailu",
    "Black Swan",
    "Blade",
    "Boothill",
    "Bronya",
    "Caelus_Harmony",
    "Clara",
    "Dan Heng",
    "Dan Heng Imbititor Lunae",
    "Dr Ratio",
    "Feixiao",
    "Firefly",
    "Fu Xuan",
    "Gallagher",
    "Gepard",
    "Guinaifen",
    "Hanya",
    "Herta",
    "Himeko",
    "Hook",
    "Huohuo",
    "Jade",
    "Jiaoqiu",
    "Jing Yuan",
    "Jingliu",
    "Kafka",
    "Lingsha",
    "Luka",
    "Luocha",
    "Lynx",
    "March 7th",
    "Misha",
    "Moze",
    "Natasha",
    "Pela",
    "Qingque",
    "Robin",
    "Ruan Mei",
    "Sampo",
    "Seele",
    "Serval",
    "Silver Wolf",
    "Sparkle",
    "Sushang",
    "Tingyun",
    "Topaz",
    "Welt",
    "Xueyi",
    "Yanqing",
    "Yukong",
    "Yunli"
];
