const contactInfo = [
    { chatName: 'Acheron', chatDesc: "Time for Departure" },
    { chatName: 'Argenti', chatDesc: "I swear to a rose" },
    { chatName: 'Blade', chatDesc: " " },
    { chatName: 'Boothill', chatDesc: "Pier Point Standard Heist (LFG 3/4)" },
    { chatName: 'Caelus', chatDesc: "I LOVE TRASH" },
    { chatName: 'Dan_Heng_Imbititor_Lunae', chatDesc: "For anything related to the data bank, come find me." },
    { chatName: 'Feixiao', chatDesc: "Itching for a fight" },
    { chatName: 'Firefly', chatDesc: "I will find a dream that is mine..." },
    { chatName: 'Fu_Xuan', chatDesc: "I do not divine personal fortunes!" },
    { chatName: 'Huohuo', chatDesc: 'Mr. Tail\'s "Tail"'},
    { chatName: 'Jade', chatDesc: "You are always welcome to Bonajade Exchange." },
    { chatName: 'Jiaoqiu', chatDesc: "There's no problem that a hot pot can't fix." },
    { chatName: 'Jingliu', chatDesc: " " },
    { chatName: 'Kafka', chatDesc: " " },
    { chatName: 'Lingsha', chatDesc: " " },
    { chatName: 'Misha', chatDesc: "Keep it up! The new world is just ahead!" },
    { chatName: 'Moze', chatDesc: "No signature." },
    { chatName: 'Seele', chatDesc: "If you have anything to say, spill it!" },
    { chatName: 'Sparkle', chatDesc: " " },
    { chatName: 'Stelle', chatDesc: "I LOVE TRASH" },
    { chatName: 'Yunli', chatDesc: "(´・ω・`) Fight?" },
    { chatName: 'Arlan', chatDesc: "Peppy's emergency contact" },
    { chatName: 'Asta', chatDesc: "I shouldn't buy any more stuff..." },
    { chatName: 'Aventurine', chatDesc: "Always open to pull for your game account" },
    { chatName: 'Bailu', chatDesc: "Drink more warm water and get fewer tempers!" },
    { chatName: 'Black_Swan', chatDesc: "Memories are soft amber" },
    { chatName: 'Bronya', chatDesc: "In a meeting" },
    { chatName: 'Clara', chatDesc: "I want to go on a picnic with everyone (>▽<)" },
    { chatName: 'Dan_Heng', chatDesc: "For anything related to the data bank, come find me." },
    { chatName: 'Dr_Ratio', chatDesc: '"There\'s no rush."'},
    { chatName: 'Gallagher', chatDesc: "Penaconian Dog" },
    { chatName: 'Gepard', chatDesc: "Working, apologies for the slow response" },
    { chatName: 'Guinaifen', chatDesc: "Not causing trouble, not fearing trouble, and no crazy challenges" },
    { chatName: 'Hanya', chatDesc: "Engaging in oneiromancy, do not disturb." },
    { chatName: 'Herta', chatDesc: "This account is disabled | Business Contact: Asta" },
    { chatName: 'Himeko', chatDesc: "I can survive without water, but coffee is my lifeblood" },
    { chatName: 'Hook', chatDesc: "Moles! Assemble at the Fight Club!" },
    { chatName: 'Jing_Yuan', chatDesc: "I'm not at the Seat of Divine Foresight" },
    { chatName: 'Luka', chatDesc: "No timely reply means I'm in training." },
    { chatName: 'Luocha', chatDesc: "A simple traveling merchant" },
    { chatName: 'Lynx', chatDesc: "The user you have messaged is currently unavailable" },
    { chatName: 'March_7th', chatDesc: "Today is also March 7th~" },
    { chatName: 'Natasha', chatDesc: "Doing outpatient runs at the Robot Settlement. Check my availability before you visit" },
    { chatName: 'Pela', chatDesc: "Please include your name when providing information" },
    { chatName: 'Qingque', chatDesc: "Go ahead and work, just don't interrupt my game" },
    { chatName: 'Robin', chatDesc: "Let's share our wings with one another." },
    { chatName: 'Ruan_Mei', chatDesc: "Those are new cakes... Where did you get them?" },
    { chatName: 'Sampo', chatDesc: "Certified ancient relic agent" },
    { chatName: 'Serval', chatDesc: "Lacking sleep and inspiration" },
    { chatName: 'Silver_Wolf', chatDesc: "Don't make a game if you don't know how to" },
    { chatName: 'Sushang', chatDesc: "What illness makes you sleepy as soon as you read a book?" },
    { chatName: 'Tingyun', chatDesc: "Let's talk it out and not fight~" },
    { chatName: 'Topaz', chatDesc: "Offsite~ Call if important, otherwise text" },
    { chatName: 'Unknown', chatDesc: "???" },
    { chatName: 'Welt', chatDesc: "Everyone on the Express, please constantly keep in touch" },
    { chatName: 'Xueyi', chatDesc: "In seclusion. Do not disturb." },
    { chatName: 'Yanqing', chatDesc: "Did the Artisanship Commission have new products today? No" },
    { chatName: 'Yukong', chatDesc: "I wish to take to the skies once more..." }
];

export default contactInfo
