import React from 'react'

function WorkskinHSR({ textRef }) {
  return (
    <div>
        <h3>Honkai Star Rail Workskin</h3>
        <div className='workskin-box' ref={textRef}>
        <p className='tiny'>#workskin .phone {'{'}</p>
        <p className='tiny'>&nbsp; max-width: 350px;</p>
        <p className='tiny'>&nbsp; font-family: Bahnschrift, Inter, sans-serif !important;</p>
        <p className='tiny'>&nbsp; display: table;</p>
        <p className='tiny'>&nbsp; margin: auto;</p>
        <p className='tiny'>&nbsp; background-color: #d4d8dc;</p>
        <p className='tiny'>&nbsp; border-radius: 0 15px 0 0;</p>
        <p className='tiny'>&nbsp; outline: 1.5px solid rgba(213, 214, 215, 0.9);</p>
        <p className='tiny'>&nbsp; outline-offset: 2px;</p>
        <p className='tiny'>&nbsp; padding-left: 1em;</p>
        <p className='tiny'>&nbsp; padding-right: 1em;</p>
        <p className='tiny'>&nbsp; padding-bottom: 1em;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'></p>
        <p className='tiny'>#workskin .msg-row:hover {'{'}</p>
        <p className='tiny'>&nbsp; background-color: #d4d8dc;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'></p>
        <p className='tiny'>#workskin .header {'{'}</p>
        <p className='tiny'>&nbsp; min-width: 350px;</p>
        <p className='tiny'>&nbsp; background: none;</p>
        <p className='tiny'>&nbsp; border-bottom: 1.5px solid #b9bdbf;</p>
        <p className='tiny'>&nbsp; margin-bottom: 1em;</p>
        <p className='tiny'>&nbsp; padding-left: .5em;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'></p>
        <p className='tiny'>#workskin .main-contact {'{'}</p>
        <p className='tiny'>&nbsp; font-size: larger;</p>
        <p className='tiny'>&nbsp; color: #121212;</p>
        <p className='tiny'>&nbsp; font-weight: bold;</p>
        <p className='tiny'>&nbsp; margin-top: .75em;</p>
        <p className='tiny'>&nbsp; margin-bottom: 0;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'></p>
        <p className='tiny'>#workskin .bio {'{'}</p>
        <p className='tiny'>&nbsp; margin: .25em auto .75em auto;</p>
        <p className='tiny'>&nbsp; color: #666868;</p>
        <p className='tiny'>&nbsp; font-size: smaller;</p>
        <p className='tiny'>&nbsp; font-weight: 600;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'></p>
        <p className='tiny'>#workskin .fulltext {'{'}</p>
        <p className='tiny'>&nbsp; min-height: fit-content;</p>
        <p className='tiny'>&nbsp; margin-right: auto;</p>
        <p className='tiny'>&nbsp; margin-left: 0px;</p>
        <p className='tiny'>&nbsp; margin-bottom: .25em;</p>
        <p className='tiny'>&nbsp; width: auto;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'></p>
        <p className='tiny'>#workskin .fullreply {'{'}</p>
        <p className='tiny'>&nbsp; min-height: fit-content;</p>
        <p className='tiny'>&nbsp; margin-right: 0px;</p>
        <p className='tiny'>&nbsp; margin-left: auto;</p>
        <p className='tiny'>&nbsp; margin-bottom: .25em;</p>
        <p className='tiny'>&nbsp; width: auto;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'>#workskin .full-reply .picture, .full-text .picture {'{'}</p>
        <p className='tiny'>&nbsp; width: 150px;</p>
        <p className='tiny'>&nbsp; height: 75px;</p>
        <p className='tiny'>&nbsp; background-color: #000;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'></p>
        <p className='tiny'>#workskin .L-contact {'{'}</p>
        <p className='tiny'>&nbsp; font-weight: 500;</p>
        <p className='tiny'>&nbsp; font-size: 90%;</p>
        <p className='tiny'>&nbsp; color: #666868;</p>
        <p className='tiny'>&nbsp; padding: 0 0 .25em .75em;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'></p>
        <p className='tiny'>#workskin .R-contact {'{'}</p>
        <p className='tiny'>&nbsp; font-weight: 500;</p>
        <p className='tiny'>&nbsp; font-size: 90%;</p>
        <p className='tiny'>&nbsp; color: #666868;</p>
        <p className='tiny'>&nbsp; padding: 0 0.75em .25em 0;</p>
        <p className='tiny'>&nbsp; text-align: right;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'></p>
        <p className='tiny'>#workskin .hsricon {'{'}</p>
        <p className='tiny'>&nbsp; width: 60px;</p>
        <p className='tiny'>&nbsp; height: 60px;</p>
        <p className='tiny'>&nbsp; border-radius: 100%;</p>
        <p className='tiny'>&nbsp; background-color: #121212;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'></p>
        <p className='tiny'>#workskin .td-icon {'{'}</p>
        <p className='tiny'>&nbsp; vertical-align: top;</p>
        <p className='tiny'>&nbsp; width: 60px;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'></p>
        <p className='tiny'>#workskin .text {'{'}</p>
        <p className='tiny'>&nbsp; font-weight: 500;</p>
        <p className='tiny'>&nbsp; float: left;</p>
        <p className='tiny'>&nbsp; color: #121212;</p>
        <p className='tiny'>&nbsp; margin: 0 0 0.75em 0.75em;</p>
        <p className='tiny'>&nbsp; border-radius: 0 .65em .65em .65em;</p>
        <p className='tiny'>&nbsp; padding: 0.5em 1em;</p>
        <p className='tiny'>&nbsp; background: #ededed;</p>
        <p className='tiny'>&nbsp; max-width: 80%;</p>
        <p className='tiny'>&nbsp; clear: both;</p>
        <p className='tiny'>&nbsp; position: relative;</p>
        <p className='tiny'>&nbsp; box-shadow: #9ea0a1 -1px 2px;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'></p>
        <p className='tiny'>#workskin .reply {'{'}</p>
        <p className='tiny'>&nbsp; font-weight: 500;</p>
        <p className='tiny'>&nbsp; float: right;</p>
        <p className='tiny'>&nbsp; color: #121212;</p>
        <p className='tiny'>&nbsp; margin: 0 .75em .75em 0;</p>
        <p className='tiny'>&nbsp; border-radius: .65em 0 .65em .65em;</p>
        <p className='tiny'>&nbsp; padding: .5em 1em;</p>
        <p className='tiny'>&nbsp; background: #d9caa9;</p>
        <p className='tiny'>&nbsp; max-width: 80%;</p>
        <p className='tiny'>&nbsp; clear: both;</p>
        <p className='tiny'>&nbsp; position: relative;</p>
        <p className='tiny'>&nbsp; box-shadow: #9ea0a1 1px 2px;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'>#workskin .full-reply .hsr-picture, .full-text .hsr-picture {'{'}</p>
        <p className='tiny'>&nbsp; width: 150px;</p>
        <p className='tiny'>&nbsp; height: 75px;</p>
        <p className='tiny'>&nbsp; background-color: #000;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'>#workskin .full-reply .hsr-sticker, .full-text .hsr-sticker {'{'}</p>
        <p className='tiny'>&nbsp; width: 75px;</p>
        <p className='tiny'>&nbsp; height: 75px;</p>
        <p className='tiny'>&nbsp; background-color: none;</p>
        <p className='tiny'>&nbsp; margin: 1rem;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'></p>
        <p className='tiny'>#workskin .full-text .hsr-picture {'{'}</p>
        <p className='tiny'>&nbsp; float: left;</p>
        <p className='tiny'>&nbsp; margin: 0.5rem 0.75rem 1rem 1.5rem;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'>#workskin .full-text .hsr-sticker {'{'}</p>
        <p className='tiny'>&nbsp; float: left;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'>#workskin .full-reply .hsr-picture {'{'}</p>
        <p className='tiny'>&nbsp; float: left;</p>
        <p className='tiny'>&nbsp; margin: 0.5rem 1.5rem 1rem 0.75rem;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'>#workskin .full-reply .hsr-sticker {'{'}</p>
        <p className='tiny'>&nbsp; float: right;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'>#workskin .fullalert {'{'}</p>
        <p className='tiny'>&nbsp; vertical-align: middle;</p>
        <p className='tiny'>&nbsp; width: fit-content;</p>
        <p className='tiny'>&nbsp; margin-left: auto;</p>
        <p className='tiny'>&nbsp; margin-right: auto;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'></p>
        <p className='tiny'>#workskin .alert-icon {'{'}</p>
        <p className='tiny'>&nbsp; width: 17.5px;</p>
        <p className='tiny'>&nbsp; height: 17.5px;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'></p>
        <p className='tiny'>#workskin .alert-display {'{'}</p>
        <p className='tiny'>&nbsp; width: fit-content;</p>
        <p className='tiny'>&nbsp; text-align: center;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'></p>
        <p className='tiny'>#workskin .alert {'{'}</p>
        <p className='tiny'>&nbsp; vertical-align: middle;</p>
        <p className='tiny'>&nbsp; text-align: left;</p>
        <p className='tiny'>&nbsp; color: #858586;</p>
        <p className='tiny'>&nbsp; font-size: small;</p>
        <p className='tiny'>&nbsp; padding-bottom: .5em;</p>
        <p className='tiny'>&nbsp; padding-top: .5em;</p>
        <p className='tiny'>&nbsp; margin: .25em 0 .75em 0em;</p>
        <p className='tiny'>&nbsp; display: table;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'></p>
        <p className='tiny'></p>
      </div>
    </div>
  )
}

export default WorkskinHSR