import React from 'react'

function WorkskinIOS({ textRef }) {
  return (
    <div className='code-box'>
        <h3>iOS Message Workskin</h3>
        <div className='workskin-box' ref={textRef}>
        <p className='tiny'>#workskin .ios-phone {'{'}</p>
        <p className='tiny'>&nbsp; font-family: Arial, Helvetica, Inter, Roboto, sans-serif;</p>
        <p className='tiny'>&nbsp; max-width: 21.875rem;</p>
        <p className='tiny'>&nbsp; display: table;</p>
        <p className='tiny'>&nbsp; margin: auto;</p>
        <p className='tiny'>&nbsp; padding-left: 1rem;</p>
        <p className='tiny'>&nbsp; padding-right: 1rem;</p>
        <p className='tiny'>&nbsp; padding-bottom: 1rem;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'></p>
        <p className='tiny'>#workskin .ios-header {'{'}</p>
        <p className='tiny'>&nbsp; background-color: #F6F6F6;</p>
        <p className='tiny'>&nbsp; min-width: 21.875rem;</p>
        <p className='tiny'>&nbsp; border-bottom: 0.094rem solid #b9bdbf;</p>
        <p className='tiny'>&nbsp; padding-bottom: 0.5rem;</p>
        <p className='tiny'>&nbsp; padding-top: 0.5rem;</p>
        <p className='tiny'>&nbsp; margin-left: -0.5rem;</p>
        <p className='tiny'>&nbsp; margin-right: -0.5em;</p>
        <p className='tiny'>&nbsp; margin-bottom: 1rem;</p>
        <p className='tiny'>&nbsp; text-align: center;</p>
        <p className='tiny'>&nbsp; text-transform: capitalize;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'></p>
        <p className='tiny'>#workskin .main-ios-contact {'{'}</p>
        <p className='tiny'>&nbsp; color: #000;</p>
        <p className='tiny'>&nbsp; font-weight: bold;</p>
        <p className='tiny'>&nbsp; margin-top: 0.75rem;</p>
        <p className='tiny'>&nbsp; margin-bottom: 0;</p>
        <p className='tiny'>&nbsp; font-size: larger;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'></p>
        <p className='tiny'>#workskin .ios-bio {'{'}</p>
        <p className='tiny'>&nbsp; margin: 0.5rem auto 0.25rem auto;</p>
        <p className='tiny'>&nbsp; color: #666868;</p>
        <p className='tiny'>&nbsp; font-size: smaller;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'></p>
        <p className='tiny'>#workskin .ios-text {'{'}</p>
        <p className='tiny'>&nbsp; float: left;</p>
        <p className='tiny'>&nbsp; color: #000000;</p>
        <p className='tiny'>&nbsp; margin: 0 0 0.5em;</p>
        <p className='tiny'>&nbsp; padding: 0.5em 1em;</p>
        <p className='tiny'>&nbsp; clear: both;</p>
        <p className='tiny'>&nbsp; position: relative;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'>#workskin .ios-reply {'{'}</p>
        <p className='tiny'>&nbsp; float: right;</p>
        <p className='tiny'>&nbsp; color: #FFFFFF;</p>
        <p className='tiny'>&nbsp; margin: 0 0 0.5em;</p>
        <p className='tiny'>&nbsp; padding: 0.5em 1em;</p>
        <p className='tiny'>&nbsp; clear: both;</p>
        <p className='tiny'>&nbsp; position: relative;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'>#workskin .full-text {'{'}</p>
        <p className='tiny'>&nbsp; margin-right: auto;</p>
        <p className='tiny'>&nbsp; margin-left: 0rem;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'>#workskin .full-text .ios-ios-text {'{'}</p>
        <p className='tiny'>&nbsp; float: left;</p>
        <p className='tiny'>&nbsp; color: #000000;</p>
        <p className='tiny'>&nbsp; margin: 0 0 0.5em;</p>
        <p className='tiny'>&nbsp; border-radius: 1em;</p>
        <p className='tiny'>&nbsp; padding: 0.5em 1em;</p>
        <p className='tiny'>&nbsp; background: #e5e5ea;</p>
        <p className='tiny'>&nbsp; max-width: 75%;</p>
        <p className='tiny'>&nbsp; clear: both;</p>
        <p className='tiny'>&nbsp; position: relative;</p>
        <p className='tiny'>&nbsp; overflow-wrap: break-word;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'>#workskin .full-text .ios-ios-text::after {'{'}</p>
        <p className='tiny'>&nbsp; content: "";</p>
        <p className='tiny'>&nbsp; position: absolute;</p>
        <p className='tiny'>&nbsp; left: -.5em;</p>
        <p className='tiny'>&nbsp; bottom: 0;</p>
        <p className='tiny'>&nbsp; width: 0.5em;</p>
        <p className='tiny'>&nbsp; height: 1em;</p>
        <p className='tiny'>&nbsp; border-right: 0.5em solid #e5e5ea;</p>
        <p className='tiny'>&nbsp; border-bottom-right-radius: 1em 0.5em;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'>#workskin .full-text .ios-ios-picture {'{'}</p>
        <p className='tiny'>&nbsp; float: left;</p>
        <p className='tiny'>&nbsp; margin: 0.5rem 0.75rem 1rem 1.5rem;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'>#workskin .full-reply {'{'}</p>
        <p className='tiny'>&nbsp; margin-right: 0rem;</p>
        <p className='tiny'>&nbsp; margin-left: auto;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'>#workskin .full-reply .ios-ios-text {'{'}</p>
        <p className='tiny'>&nbsp; float: right;</p>
        <p className='tiny'>&nbsp; color: #FFFFFF;</p>
        <p className='tiny'>&nbsp; margin: 0 0 0.5em;</p>
        <p className='tiny'>&nbsp; border-radius: 1em;</p>
        <p className='tiny'>&nbsp; padding: 0.5em 1em;</p>
        <p className='tiny'>&nbsp; background: #1289fe;</p>
        <p className='tiny'>&nbsp; max-width: 75%;</p>
        <p className='tiny'>&nbsp; clear: both;</p>
        <p className='tiny'>&nbsp; position: relative;</p>
        <p className='tiny'>&nbsp; overflow-wrap: break-word;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'>#workskin .full-reply .ios-ios-text::after {'{'}</p>
        <p className='tiny'>&nbsp; content: "";</p>
        <p className='tiny'>&nbsp; position: absolute;</p>
        <p className='tiny'>&nbsp; right: -0.5em;</p>
        <p className='tiny'>&nbsp; bottom: 0;</p>
        <p className='tiny'>&nbsp; width: 0.5em;</p>
        <p className='tiny'>&nbsp; height: 1em;</p>
        <p className='tiny'>&nbsp; border-left: 0.5em solid #1289fe;</p>
        <p className='tiny'>&nbsp; border-bottom-left-radius: 1em 0.5em;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'>#workskin .full-reply .ios-ios-picture {'{'}</p>
        <p className='tiny'>&nbsp; float: right;</p>
        <p className='tiny'>&nbsp; margin: 0.5rem 1.5rem 1rem 0.75rem;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'>#workskin .sender-contact {'{'}</p>
        <p className='tiny'>&nbsp; font-weight: 500;</p>
        <p className='tiny'>&nbsp; font-size: 90%;</p>
        <p className='tiny'>&nbsp; color: #666868;</p>
        <p className='tiny'>&nbsp; padding: 0 0 0.25rem 0.75rem;</p>
        <p className='tiny'>&nbsp; float: left;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'>#workskin .receiver-contact {'{'}</p>
        <p className='tiny'>&nbsp; font-weight: 500;</p>
        <p className='tiny'>&nbsp; font-size: 90%;</p>
        <p className='tiny'>&nbsp; color: #666868;</p>
        <p className='tiny'>&nbsp; padding: 0 0.75rem 0.25rem 0;</p>
        <p className='tiny'>&nbsp; text-align: right;</p>
        <p className='tiny'>&nbsp; float: right;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'>#workskin .fullalert {'{'}</p>
        <p className='tiny'>&nbsp; vertical-align: middle;</p>
        <p className='tiny'>&nbsp; width: -moz-fit-content;</p>
        <p className='tiny'>&nbsp; width: fit-content;</p>
        <p className='tiny'>&nbsp; margin-left: auto;</p>
        <p className='tiny'>&nbsp; margin-right: auto;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'>#workskin .alert-display {'{'}</p>
        <p className='tiny'>&nbsp; width: -moz-fit-content;</p>
        <p className='tiny'>&nbsp; width: fit-content;</p>
        <p className='tiny'>&nbsp; text-align: center;</p>
        <p className='tiny'>{'}'}</p>
        <p className='tiny'></p>
        <p className='tiny'>#workskin .alert {'{'}</p>
        <p className='tiny'>&nbsp; vertical-align: middle;</p>
        <p className='tiny'>&nbsp; text-align: left;</p>
        <p className='tiny'>&nbsp; color: #858586;</p>
        <p className='tiny'>&nbsp; font-size: small;</p>
        <p className='tiny'>&nbsp; padding-bottom: 0.5rem;</p>
        <p className='tiny'>&nbsp; padding-top: 0.5rem;</p>
        <p className='tiny'>&nbsp; margin: 0.25rem 0 0.75rem 0rem;</p>
        <p className='tiny'>&nbsp; display: table;</p>
        <p className='tiny'>{'}'}</p>
      </div>
    </div>
  )
}

export default WorkskinIOS